/** @type {import('tailwindcss').Config} */
module.exports = {
    prefix: 'tw-',
    content: ["./**/*.{razor,html,cshtml}"],
    safelist: [
        "validation-message",
        "tab-active",
        'text-success',
        'text-error',
        'fill-primary',
        'btn',
        'btn-primary',
        'btn-secondary',
        'btn-accent',
        'btn-success',
        'btn-error',
        'btn-warning',
        'btn-info',
        'btn-ghost',
        'btn-link',
        'btn-xs',
        'btn-sm',
        'btn-lg',
        'btn-block',
        'btn-wide',
        'btn-circle',
        'btn-square',
        'active',
        'alert-info',
        'alert-success',
        'alert-warning',
        'alert-error',
        'duration-300',
        'translate-x-0',
        'opacity-100',
        'translate-x-full',
        'opacity-0',
        'delay-100',
        'animate-spin',
        'modal-open',
        '-ml-1',
        'mr-3',
        'h-5',
        'h-10',
        'w-5',
        'w-10',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}
