/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./**/*.{razor,html,cshtml}"],
    safelist: [
        "validation-message",
        "tab-active",
        'text-success',
        'text-error',
        'fill-primary',
        'btn',
        'btn-primary',
        'btn-xs',
        'btn-sm',
        'btn-lg',
        'btn-block',
        'btn-wide',
        'btn-circle',
        'btn-wide',
        'active',
        'alert-info',
        'alert-success',
        'alert-warning',
        'alert-error',
        'duration-300',
        'translate-x-0',
        'opacity-100',
        'translate-x-full',
        'opacity-0',
        'delay-100',
        'animate-spin',
        '-ml-1',
        'mr-3',
        'h-5',
        'h-10',
        'w-5',
        'w-10',
    ],
    theme: {
        extend: {},
    },
    plugins: [require("daisyui")],
}
