global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.SignalR;
global using gbs.Server.Data;
global using gbs.Shared.Entities;
global using gbs.Shared.Dtos.Students;
global using gbs.Server.Hubs;
global using gbs.Server.Repository.StudentRepository;
global using gbs.Server.Repository.TeacherRepository;